# Package definition for just

package_name: just
github_repo: casey/just
license: CC0-1.0
artifact_format: tar.gz
description: "Just a command runner"
license: CC0-1.0

# Build for all Debian suites and all supported architectures.
